### ISSUE TITLE
Deploy details Deploy failed

### ISSUE THREAD

**Issue by thimiraonline** [TryGhost/algolia#41]
11:19:38 AM: ────────────────────────────────────────────────────────────────
11:19:38 AM:   Configuration error                                           
11:19:38 AM: ────────────────────────────────────────────────────────────────
11:19:38 AM: ​
11:19:38 AM:   Error message
11:19:38 AM:   Deploy did not succeed: Deploy directory 'packages/algolia-netlify/dist' does not exist
11:19:38 AM: ​
11:19:38 AM:   Resolved config
11:19:38 AM:   build:
11:19:38 AM:     base: /opt/build/repo/packages/algolia-netlify
11:19:38 AM:     command: NODE_ENV=production yarn build
11:19:38 AM:     commandOrigin: config
11:19:38 AM:     environment:
11:19:38 AM:       - ALGOLIA_ACTIVE
11:19:38 AM:       - ALGOLIA_API_KEY
11:19:38 AM:       - ALGOLIA_APP_ID
11:19:38 AM:       - ALGOLIA_INDEX
11:19:38 AM:       - NODE_VERSION
11:19:38 AM:       - AWS_LAMBDA_JS_RUNTIME
11:19:38 AM:     publish: /opt/build/repo/packages/algolia-netlify/dist
11:19:38 AM:     publishOrigin: ui
11:19:38 AM:   functionsDirectory: /opt/build/repo/packages/algolia-netlify/build/functions
11:19:39 AM: Caching artifacts

**Comment by miphilomath** [comment]
Faced similar issue. Update the deploy settings in netlify and remove the publish directory from build settings. 
![image](https://user-images.githubusercontent.com/26297035/163672101-c4f74a60-cb5b-44d8-a54f-ff1f76a80a2a.png)
